name: Keep Render Service Awake

on:
  schedule:
    - cron: '*/14 * * * *'   # Runs every 14 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render service
        run: curl -fsS --retry 3 https://web-search-tool-calling.onrender.com
